// This file is auto-generated by `ember build`.
// You should not modify it.

var App = window.App = require('./config/app');
require('./templates');


App.CategoryController = require('./controllers/category_controller');
App.EditCategoryController = require('./controllers/edit_category_controller');
App.EditTransactionController = require('./controllers/edit_transaction_controller');
App.NewCategoryController = require('./controllers/new_category_controller');
App.NewTransactionController = require('./controllers/new_transaction_controller');
App.TransactionController = require('./controllers/transaction_controller');
App.Category = require('./models/category');
App.Transaction = require('./models/transaction');
App.CategoriesRoute = require('./routes/categories_route');
App.NewCategoryRoute = require('./routes/new_category_route');
App.NewTransactionRoute = require('./routes/new_transaction_route');
App.TransactionsRoute = require('./routes/transactions_route');

require('./config/routes');

module.exports = App;

